### ISSUE TITLE
custom header

### ISSUE THREAD

**Issue by brody182** [neilgee/genesischild#10]
why do i see this message on pages?  "Oh No!! You have custom_header activated in your functions.php. Open that file and remove: add_theme_support( 'custom-header' ); "

**Comment by neilgee** [comment]
Maybe a plugin you have is looking after the custom header, do you use any for that?

**Comment by dannybeddows** [comment]
Hi, Neil your Genesis child theme is awesome - thanks so much. (Not sure if this was in response to a support request I made but I fixed the issue I was having with the front page) was just something like above that I had to switch in functions.php so cheers a lot!.

**Comment by brody182** [comment]
nope its the custom-header function you use for the logo in function.php. if you try it you can see it in pages, latest version of wordpress

**Comment by neilgee** [comment]
Can't replicate the error - tested on latest version with WP Debug on, the function is the just the regular one from the codex https://codex.wordpress.org/Custom_Headers

**Comment by neilgee** [comment]
Hi Danny - thanks for the feedback

**Comment by brody182** [comment]
look a little harder, its only on pages

**Comment by neilgee** [comment]
you got some cheek

**Comment by brody182** [comment]
lol

**Comment by berserkia** [comment]
@brody182 that happens if you have another plugin that interacts with the header (like Genesis Simple Headers, Genesis Logo upload, etc.) activated on your site. If you deactivate other plugins that try to alter the header, you should be set.
