### ISSUE TITLE
Reset from normalize.css

### ISSUE THREAD

**Issue by neil** [neilgee/genesischild#12]
Hi Neil
I don't know enough about this but I wonder if the reset is correct in style.css. 
Version 4 of normalize.css looks like it starts with html font reset.
That's also how it appears in the Genesis Sample Theme.
Sorry if this is inconsequential - I'm just curious about the difference here.
Thanks

**Comment by neilgee** [comment]
Hi Neil, that's just how the minification tool I used to minify normalize CSS did it - the html font reset is in there just further down the line, so will be ok when rendered.

If you put this - https://necolas.github.io/normalize.css/4.1.1/normalize.css 
though that - https://cssminifier.com/ you'll see what I mean.

Cheers

**Comment by neil** [comment]
Thanks Neil!
That's interesting. Sorry to be a nuisance. 
I think I was thrown by the colour coding in Atom. 
http://5lx.co.uk/images/Screenshot%202016-08-01%2008.54.35.png
Yours is on the left. I still don't understand the difference but life's too short to worry about that... :)

Cheers

**Comment by neilgee** [comment]
I see what you mean - i checked it also in Atom and I see that there is a an issue with the highlighting, I ran the CSS though a linting program just to make sure and it came out fine - also checked it on another minify tool which retains the CSS order but still had syntax hightlight oddity.

**Comment by neil** [comment]
Yep, it's a strange one. Sorry to waste your time.
This whole thing started because I struggled to style a submit button but I got it sorted anyway!

Cheers

**Comment by neilgee** [comment]
you got me curious - i double checked a SP theme and same thing with syntax highlighting (in Atom anyway) - must just be an anomaly with minified CSS

![screen shot 2016-08-02 at 8 21 15 am](https://cloud.githubusercontent.com/assets/2056045/17310851/63bf00c6-588a-11e6-913e-fd6ac98546e3.png)

**Comment by neil** [comment]
Yes I did wonder if it was actually all working as expected. The sample theme had a lot of greyed out reset text in Atom. As you say Neil, probably an anomaly.
