### ISSUE TITLE
Multiple Widgets in Widgetized Areas

### ISSUE THREAD

**Issue by 4Progress** [neilgee/genesischild#8]
If I'm using the issue section wrong, please let me know - I'm relatively new to using github.

I've set up a version of this widgetized child theme. I'd like to put more than one widget in the newly defined sections (1-3 widgets in Home Left, Home Middle, Home Right). However, when I add more than one widget it breaks the layout. More than one widget either pushes widgets to different sections, resulting in the second widget under Home Middle to be the first widget in Home Right, or it will leave a widget-sized white space where the top widgets would (gap below the nav/header) with the Home Left near the top.

I'm wondering why this is. Is having multiple widgets per added widgetized section not compatible with this theme?

To demonstrate this issue I've added screenshots of the live front-page and the Wordpress widget section.

![screen shot 2014-12-09 at 4 02 38 pm](https://cloud.githubusercontent.com/assets/4984698/5366803/5e710586-7fbc-11e4-8f9d-f08f4ce9be1b.png)
![screen shot 2014-12-09 at 4 02 19 pm](https://cloud.githubusercontent.com/assets/4984698/5366804/5e724ce8-7fbc-11e4-9b9a-7740d4997d57.png)

Based on the Wordpress widget set-up, "Important Links" should be below the center article excerpt. (Note: My menu is styled differently, but I've found this same issue using the out-of-the-box widgetized child theme).

How can I achieve what I'm after? Will I have to define and style new widgetized sections in fuctions.php and style.css?

**Comment by neilgee** [comment]
Hi, yes I see what you mean, I had only had one widget per area in mind when I added this area in.

I have now adjusted the markup so any widget added to either left, middle or right will stay in that area. The columns now will not flow.
